//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mufteev_Shoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int product_item_id { get; set; }
        public int quantity { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual stock_items stock_items { get; set; }
    }
}
