//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mufteev_Shoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.stock_items = new HashSet<stock_items>();
        }
    
        public int id { get; set; }
        public int category_id { get; set; }
        public int subcategory_id { get; set; }
        public int manufacturer_id { get; set; }
        public string title { get; set; }
        public string image_url { get; set; }
        public string description { get; set; }
        public string composition { get; set; }
        public decimal price { get; set; }
    
        public virtual categories categories { get; set; }
        public virtual manufacturers manufacturers { get; set; }
        public virtual subcategories subcategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_items> stock_items { get; set; }
    }
}
