//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mufteev_Shoe
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.stock_items = new HashSet<stock_items>();
        }
    
        public int id { get; set; }
        public int category_id { get; set; }
        public int subcategory_id { get; set; }
        public int manufacturer_id { get; set; }
        public string title { get; set; }
        public string image_url { get; set; }
        public string CorrectImagePath
        {
            get
            {
                if (string.IsNullOrEmpty(image_url))
                {
                    return "/res/picture.png";
                }
                return $"/res/images/{image_url}";
            }
        }
        public string description { get; set; }
        public string composition { get; set; }
        public decimal price { get; set; }

        public int TotalQuantity
        {
            get
            {
                // Если у товара нет записей об остатках в таблице stock_items — возвращаем 0
                if (this.stock_items == null || this.stock_items.Count == 0)
                    return 0;

                // Складываем колонку quantity из связанной таблицы остатков
                return this.stock_items.Sum(s => s.quantity);
            }
        }

        // 2. Свойство определяет цвет фона карточки на основе ТЗ
        public System.Windows.Media.SolidColorBrush CardBackground
        {
            get
            {
                // Если суммарный остаток по всем размерам меньше или равен 3 — возвращаем цвет #ff8080
                if (TotalQuantity <= 3)
                {
                    return (System.Windows.Media.SolidColorBrush)new System.Windows.Media.BrushConverter().ConvertFromString("#ff8080");
                }

                // Иначе оставляем обычный белый фон карточки товара
                return (System.Windows.Media.SolidColorBrush)new System.Windows.Media.BrushConverter().ConvertFromString("#FFFFFF");
            }
        }

        public virtual categories categories { get; set; }
        public virtual manufacturers manufacturers { get; set; }
        public virtual subcategories subcategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock_items> stock_items { get; set; }
    }
}
