//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mufteev_Shoe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MufteevShoeDBEntities : DbContext
    {
        private static MufteevShoeDBEntities _context;

        public static MufteevShoeDBEntities GetContext()
        {
            if(_context == null)
                _context = new MufteevShoeDBEntities();
            return _context;
        }
        public MufteevShoeDBEntities()
            : base("name=MufteevShoeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<manufacturers> manufacturers { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<sizes> sizes { get; set; }
        public virtual DbSet<stock_items> stock_items { get; set; }
        public virtual DbSet<subcategories> subcategories { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
